#!/bin/bash

print_help () {
    echo "Usage: $0 [-s|--standalone|-v|--version]"
    echo "    -s|--standalone -> Put pandoc HTML wrapper around the content."
    echo "    -v|--version -> Put the output files under defined folder name."
    exit 1
}

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
standalone=0
version="v0.1.2"

while [[ $# > 0 ]]; do
    key="$1"
    case $key in
        -s|--standalone)
        standalone=1
        shift
        ;;
        -v|--version)
        shift
        version=$1
        shift
        ;;
        -h|--help|help)
        print_help
        shift
        ;;
    esac
done

input_dir=${script_dir}/../../products/lab/${version}
output_dir=${script_dir}/../../output/html/lab/${version}

# TODO: add support for the title with spaces
append_standalone () {
    (( $standalone )) && \
    echo "--metadata=title:'$1' --metadata=html_link_suffix:'' --metadata=html_link_prefix:'.html'" || \
    echo "--metadata=html_link_suffix:'/docs/lab/${version}/' --metadata=html_link_prefix:''"
}

rm -rf ${output_dir}
mkdir -p ${output_dir}

cd ${script_dir}
source ve3/bin/activate || exit 1

# Generate HTML files.
pandoc ${input_dir}/README.md --from markdown --to html --output ${output_dir}/index.html --filter ${script_dir}/links_filter.py $(append_standalone "TechnicalDocumentation") || exit 1
pandoc ${input_dir}/how_to_install_memgraph_lab_on_macos.md --from markdown --to html --output ${output_dir}/how_to_install_memgraph_lab_on_macos.html --filter ${script_dir}/links_filter.py $(append_standalone "HowToInstallMemgraphLabOnMacOS") || exit 1

# Copy data files.
mkdir -p ${output_dir}/data
cp -r ${input_dir}/data/* ${output_dir}/data/

deactivate

echo "Output dir: $output_dir"
