#!/bin/bash

print_help () {
    echo "Usage: $0 [--standalone]"
    echo -e "\t--standalone\tGenerate standalone HTML documents."
    echo -e "\t-h|--help\tPrint help."
}

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

versions=("v0.13.0" "v0.14.1")
# Parse inputs.
standalone=0
if [[ $# -gt 1 ]]; then
    print_help
    exit 1
elif  [[ $# -eq 1 ]]; then
    case "$1" in
        --standalone)
            standalone=1
        ;;
        -h|--help)
            print_help
            exit 0
        ;;
        *)
            print_help
            exit 1
        ;;
    esac
fi

# Generate output folders.
mkdir -p ${script_dir}/../../output/html/memgraph

# Initialize HTML gen environment.
if [ ! -d "${script_dir}/ve3" ]; then
    virtualenv -p python3 ve3 || exit 1
    source ve3/bin/activate
    pip install -r ${script_dir}/requirements.txt || exit 1
    deactivate
fi


fail_with_msg () {
    echo ${1}
    exit 1
}

add_link_info () {
    local resource_dir=$(dirname $1)
    if [[ ${resource_dir} == "." ]]; then
        resource_dir=""
    else
        resource_dir="${resource_dir}/"
    fi
    (( $standalone )) && \
    echo "--metadata=html_link_suffix:'' --metadata=html_link_prefix:'.html'" || \
    echo "--metadata=html_link_suffix:'/docs/memgraph/${version}/${resource_dir}' --metadata=html_link_prefix:''"
}

dump_html () {
    # Info about the relative path has to be preserved because non standalone
    # generator depends on that.
    local src_dir=$1
    local src_relpath=$2
    local dst_dir=$3
    local dst_relpath=$4
    pandoc ${src_dir}/${src_relpath} \
        --from markdown --to html \
        --output ${dst_dir}/${dst_relpath} \
        --filter ${script_dir}/links_filter.py \
        $(add_link_info ${dst_relpath}) || fail_with_msg "Failed to generate ${dst_relpath}!"
}

generate_version () {
    version=$1
    input_dir=${script_dir}/../../products/memgraph/${version}
    output_dir=${script_dir}/../../output/html/memgraph/${version}

    rm -rf ${output_dir}
    mkdir -p ${output_dir}
    mkdir -p ${output_dir}/concepts
    mkdir -p ${output_dir}/how_to_guides
    mkdir -p ${output_dir}/reference_guide
    mkdir -p ${output_dir}/tutorials
    mkdir -p ${output_dir}/data
    cd ${script_dir}
    source ve3/bin/activate || exit 1

    cp -r ${input_dir}/data/* ${output_dir}/data/
    dump_html ${input_dir} "README.md" ${output_dir} "index.html"
    dump_html ${input_dir} "LICENSE.md" ${output_dir} "license.html"
    dump_html ${input_dir} "faq.md" ${output_dir} "faq.html"
    dump_html ${input_dir} "quick-start.md" ${output_dir} "quick-start.html"
    dump_html ${input_dir} "upcoming-features.md" ${output_dir} "upcoming-features.html"
    for dir in $(find ${input_dir}/* -maxdepth 1 -type d); do
        for file in "$dir"/*; do
            rel_path=$(realpath --relative-to=${input_dir} ${dir})
            if [[ "${rel_path}" == "data" ]]; then
                continue
            fi
            basename=$(basename ${file%.*})
            dump_html ${input_dir} "${rel_path}/${basename}.md" ${output_dir} "${rel_path}/${basename}.html"
        done
    done
    deactivate
    echo "Output Diractory: $output_dir"
}

cd ${script_dir}
source ve3/bin/activate || exit 1
dump_html ${script_dir}/../../products/memgraph "CHANGELOG.md" ${script_dir}/../../output/html/memgraph "changelog.html"
for version in "${versions[@]}"; do
    generate_version ${version}
done
