#!/bin/bash

print_help () {
    echo "Usage: $0 [--no-standalone]"
    echo "    --no-standalone -> Don't put pandoc HTML wrapper around the content."
    exit 1
}

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

standalone=1
while [[ $# > 0 ]]; do
    key="$1"
    case $key in
        --no-standalone)
        standalone=0
        shift
        ;;
        -h|--help|help)
        print_help
        shift
        ;;
    esac
done

# Generate output folders.
mkdir -p ${script_dir}/output/pdf
mkdir -p ${script_dir}/output/html

# Setup HTML environment.
cd ${script_dir}/format/html
if [ ! -d "${script_dir}/format/html/ve3" ]; then
    virtualenv -p python3 ve3 || exit 1
    source ve3/bin/activate
    pip install -r ${script_dir}/format/html/requirements.txt || exit 1
    deactivate
fi

append_standalone () {
    (( $standalone )) && \
    echo "--standalone" || \
    echo ""
}

# Generate Memgraph DBMS docs.
./generate_memgraph_v0.12.0 $(append_standalone)
versions=("v0.13.0" "v0.14.0")
for version in "${versions[@]}"; do
    ./generate_memgraph --version ${version} $(append_standalone)
done

# Generate Memgraph Lab docs.
./generate_lab $(append_standalone)
