#!/bin/bash

print_help () {
    echo "Usage: $0 [--standalone]"
    echo -e "\t--standalone\tGenerate standalone HTML documents."
    echo -e "\t-h|--help\tPrint help."
}

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Parse inputs.
standalone=0
if [[ $# -gt 1 ]]; then
    print_help
    exit 1
elif  [[ $# -eq 1 ]]; then
    case "$1" in
        --standalone)
            standalone=1
        ;;
        -h|--help)
            print_help
            exit 0
        ;;
        *)
            print_help
            exit 1
        ;;
    esac
fi

# Generate output folders.
mkdir -p ${script_dir}/output/html

# Initialize HTML gen environment.
cd ${script_dir}/format/html
if [ ! -d "${script_dir}/format/html/ve3" ]; then
    virtualenv -p python3 ve3 || exit 1
    source ve3/bin/activate
    pip install -r ${script_dir}/format/html/requirements.txt || exit 1
    deactivate
fi

append_standalone () {
    (( $standalone )) && \
    echo "--standalone" || \
    echo ""
}

# Generate Memgraph docs.
./generate_memgraph $(append_standalone)

# Generate Memgraph Lab docs.
./generate_lab $(append_standalone)
