module.exports = {
  cypher_manual: [
    'overview',
    'reading-existing-data',
    'writing-new-data',
    'reading-and-writing',
    'functions',
    {
      type: 'category',
      label: 'Clauses',
      items: ['clauses/clauses',
        'clauses/create',
        'clauses/delete',
        'clauses/match',
        'clauses/merge',
        'clauses/optional-match',
        'clauses/remove',
        'clauses/return',
        'clauses/set',
        'clauses/union',
        'clauses/unwind',
        'clauses/where',
        'clauses/with',],
    },
    'other-features',
    'differences',
  ],
};