module.exports = {
  memgraph: [
    'overview',
    {
      type: 'category',
      label: 'Getting started',
      items: ['getting-started/getting-started',
        'getting-started/installation',
        {
          type: 'category',
          label: 'Querying the database',
          items: ['getting-started/querying/querying',
            {
              type: 'link',
              label: 'Memgraph Lab',
              href: 'https://docs.memgraph.com/memgraph-lab'
            },
            {
              type: 'link',
              label: 'Memgraph Playground',
              href: 'https://playground.memgraph.com/'
            }],
        },
        {
          type: 'category',
          label: 'Building applications',
          items: ['getting-started/connecting-applications/connecting-applications',
            'getting-started/connecting-applications/python',
            'getting-started/connecting-applications/rust',
            'getting-started/connecting-applications/c-sharp',
            'getting-started/connecting-applications/java',
            'getting-started/connecting-applications/go',
            'getting-started/connecting-applications/javascript',
            'getting-started/connecting-applications/php'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Installation',
      items: [
        {
          type: 'category',
          label: 'Linux',
          items: ['installation/linux/docker-installation',
            'installation/linux/ubuntu-installation',
            'installation/linux/debian-installation',
            'installation/linux/rpm-installation',
            'installation/linux/linux-installation-troubleshooting',],
        },
        {
          type: 'category',
          label: 'macOS',
          items: ['installation/macos/docker-installation',
            'installation/macos/macos-installation-troubleshooting',],
        },
        {
          type: 'category',
          label: 'Windows',
          items: ['installation/windows/docker-installation',
            'installation/windows/wsl-installation',
            'installation/windows/windows-installation-troubleshooting',],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: ['tutorials/tutorials',
        'tutorials/analyzing-ted-talks',
        'tutorials/backpacking-through-europe',
        'tutorials/exploring-the-european-road-network',
        'tutorials/football-transfers',
        'tutorials/graphing-the-premier-league',
        'tutorials/marvel-universe',
        'tutorials/movie-recommendation',
        'tutorials/got-deaths',
        'tutorials/social-network-analysis',
        'tutorials/understanding-music-with-modules'],
    },
    {
      type: 'category',
      label: 'Database functionalities',
      items: ['database-functionalities/database-functionalities',
        'database-functionalities/import-data',
        'database-functionalities/inspecting-queries',
        'database-functionalities/profiling-queries',
        'database-functionalities/tensorflow-setup',
        'database-functionalities/replication',
        'database-functionalities/triggers',
        'reference-guide/backup',
        'database-functionalities/memory-control',
        {
          type: 'category',
          label: 'Enforcing constraints',
          items: ['database-functionalities/constraints/existence-constraint',
            'database-functionalities/constraints/uniqueness-constraint'],
        },
        {
          type: 'category',
          label: 'Query modules',
          items: ['database-functionalities/query-modules/built-in-query-modules',
            'database-functionalities/query-modules/load-call-query-modules',
            'database-functionalities/query-modules/implement-query-modules'],
        },
        'database-functionalities/manage-user-privileges',
        'database-functionalities/manage-users-using-ldap',],
    },
    {
      type: 'category',
      label: 'Reference guide',
      items: ['reference-guide/reference-guide',
        'reference-guide/configuration',
        'reference-guide/indexing',
        'reference-guide/graph-algorithms',
        'reference-guide/tensorflow',
        'reference-guide/replication',
        'reference-guide/backup',
        {
          type: 'category',
          label: 'Query modules',
          items: ['reference-guide/query-modules/query-modules',
            'reference-guide/query-modules/c-api',
            'reference-guide/query-modules/python-api',],
        },
        {
          type: 'category',
          label: 'NetworkX',
          items: ['reference-guide/networkx/networkx',
            'reference-guide/networkx/graph-analyzer',
            'reference-guide/networkx/nxalg',
            'reference-guide/networkx/wcc',],
        },
        'reference-guide/security',
        'reference-guide/auth-module',
        'reference-guide/ldap-security',
        'reference-guide/audit-log',],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: ['concepts/concepts',
        'concepts/storage',
        'concepts/graph-algorithms',
        'concepts/indexing',
        'concepts/replication',
        'concepts/telemetry',],
    },
    {
      type: 'category',
      label: 'Drivers',
      items: [{
        type: 'link',
        label: 'C/C++',
        href: 'https://github.com/memgraph/mgclient'
      },
      {
        type: 'link',
        label: 'CLI Console',
        href: 'https://github.com/memgraph/mgconsole'
      },
      {
        type: 'link',
        label: 'Python',
        href: 'https://github.com/memgraph/pymgclient'
      },
      {
        type: 'link',
        label: 'Rust',
        href: 'https://github.com/memgraph/rsmgclient'
      },],
    },
    'upcoming-features',
    'changelog',
    {
      type: 'category',
      label: 'Getting help',
      items: ['getting-help/getting-help',
        'getting-help/faq',],
    },
  ],
};
