#!/bin/bash

print_help () {
    echo "Usage: $0 [-s|--standalone]"
    echo "    -s|--stanalone -> Put pandoc HTML wrapper around the content."
    exit 1
}

version="v1.0.0"
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
input_dir=${script_dir}/../user_technical/${version}
output_dir=${script_dir}/docs/${version}
standalone=0

while [[ $# > 0 ]]; do
    key="$1"
    case $key in
        -s|--standalone)
        standalone=1
        shift
        ;;
        -h|--help|help)
        print_help
        shift
        ;;
    esac
done

# TODO: add support for the title with spaces
append_standalone () {
    (( $standalone )) && echo "metadata.yaml --metadata title='$1' --include-after-body=footer.html" || echo ""
}

rm -rf ${output_dir}
mkdir -p ${output_dir}

cp -R ${script_dir}/libs ${script_dir}/docs/

# For each version there should be a block of code that generates appropriate
# html files. For each version a new block of code has to be added but it's ok
# for now. The goal is to learn the pattern.
if [[ "${version}" == "v0.12.0" ]]; then
    # TODO: DRY
    pandoc ${script_dir}/../user_technical/CHANGELOG.md --from markdown --to html --output ${output_dir}/changelog.html --filter ${script_dir}/html_links_filter.py $(append_standalone "Changelog")
    pandoc ${script_dir}/../user_technical/faq.md --from markdown --to html --output ${output_dir}/faq.html --filter ${script_dir}/html_links_filter.py $(append_standalone "FAQ")
    pandoc ${input_dir}/concepts.md --from markdown --to html --output ${output_dir}/concepts.html --filter ${script_dir}/html_links_filter.py $(append_standalone "Concepts")
    pandoc ${input_dir}/drivers.md --from markdown --to html --output ${output_dir}/drivers.html --filter ${script_dir}/html_links_filter.py $(append_standalone "Drivers")
    pandoc ${input_dir}/examples.md --from markdown --to html --output ${output_dir}/examples.html --filter ${script_dir}/html_links_filter.py $(append_standalone "Examples")
    pandoc ${input_dir}/import-tools.md --from markdown --to html --output ${output_dir}/import-tools.html --filter ${script_dir}/html_links_filter.py $(append_standalone "ImportTools")
    pandoc ${input_dir}/open-cypher.md --from markdown --to html --output ${output_dir}/open-cypher.html --filter ${script_dir}/html_links_filter.py $(append_standalone "openCypher")
    pandoc ${input_dir}/quick-start.md --from markdown --to html --output ${output_dir}/quick-start.html --filter ${script_dir}/html_links_filter.py $(append_standalone "QuickStart")
    pandoc ${input_dir}/storage.md --from markdown --to html --output ${output_dir}/storage.html --filter ${script_dir}/html_links_filter.py $(append_standalone "Storage")
    pandoc ${input_dir}/upcoming-features.md --from markdown --to html --output ${output_dir}/upcoming-features.html --filter ${script_dir}/html_links_filter.py $(append_standalone "UpcomingFeatures")
    pandoc ${input_dir}/README.md --from markdown --to html --output ${output_dir}/index.html --filter ${script_dir}/html_links_filter.py $(append_standalone "Index")
fi

if [[ "${version}" == "v1.0.0" ]]; then
    mkdir -p ${output_dir}/concepts
    mkdir -p ${output_dir}/how_to_guides
    mkdir -p ${output_dir}/reference_guide
    mkdir -p ${output_dir}/tutorials

    pandoc ${script_dir}/../user_technical/CHANGELOG.md --from markdown --to html --output ${output_dir}/changelog.html --filter ${script_dir}/html_links_filter.py $(append_standalone "Changelog")
    pandoc ${script_dir}/../user_technical/faq.md --from markdown --to html --output ${output_dir}/faq.html --filter ${script_dir}/html_links_filter.py $(append_standalone "FAQ")
    pandoc ${input_dir}/README.md --from markdown --to html --output ${output_dir}/index.html --filter ${script_dir}/html_links_filter.py $(append_standalone "Index")


    pandoc ${input_dir}/quick-start.md --from markdown --to html --output ${output_dir}/quick-start.html --filter ${script_dir}/html_links_filter.py $(append_standalone "QuickStart")
    pandoc ${input_dir}/upcoming-features.md --from markdown --to html --output ${output_dir}/upcoming-features.html --filter ${script_dir}/html_links_filter.py $(append_standalone "UpcomingFeatures")

    pandoc ${input_dir}/concepts/01_concepts-overview.md --from markdown --to html --output ${output_dir}/concepts/concepts-overview.html --filter ${script_dir}/html_links_filter.py $(append_standalone "ConceptsOverview")
    pandoc ${input_dir}/concepts/02_storage.md --from markdown --to html --output ${output_dir}/concepts/storage.html --filter ${script_dir}/html_links_filter.py $(append_standalone "Storage")
    pandoc ${input_dir}/concepts/03_graph-algorithms.md --from markdown --to html --output ${output_dir}/concepts/graph-algorithms.html --filter ${script_dir}/html_links_filter.py $(append_standalone "GraphAlgorithms")
    pandoc ${input_dir}/concepts/04_indexing.md --from markdown --to html --output ${output_dir}/concepts/indexing.html --filter ${script_dir}/html_links_filter.py $(append_standalone "Indexing")

    pandoc ${input_dir}/how_to_guides/01_how-to-guides-overview.md --from markdown --to html --output ${output_dir}/how_to_guides/how-to-guides-overview.html --filter ${script_dir}/html_links_filter.py $(append_standalone "HowToGuidesOverview")
    pandoc ${input_dir}/how_to_guides/02_import-tools.md --from markdown --to html --output ${output_dir}/how_to_guides/import-tools.html --filter ${script_dir}/html_links_filter.py $(append_standalone "ImportTools")
    pandoc ${input_dir}/how_to_guides/03_programmatic-querying.md --from markdown --to html --output ${output_dir}/how_to_guides/programmatic-querying.html --filter ${script_dir}/html_links_filter.py $(append_standalone "ProgrammaticQuerying")
    pandoc ${input_dir}/how_to_guides/04_how-to-ingest-data-using-kafka.md --from markdown --to html --output ${output_dir}/how_to_guides/how-to-ingest-data-using-kafka.html --filter ${script_dir}/html_links_filter.py $(append_standalone "HowToKafka")

    pandoc ${input_dir}/reference_guide/01_reference-overview.md --from markdown --to html --output ${output_dir}/reference_guide/reference-overview.html --filter ${script_dir}/html_links_filter.py $(append_standalone "ReferenceOverview")
    pandoc ${input_dir}/reference_guide/02_reading-existing-data.md --from markdown --to html --output ${output_dir}/reference_guide/reading-existing-data.html --filter ${script_dir}/html_links_filter.py $(append_standalone "ReadingExistingData")
    pandoc ${input_dir}/reference_guide/03_writing-new-data.md --from markdown --to html --output ${output_dir}/reference_guide/writing-new-data.html --filter ${script_dir}/html_links_filter.py $(append_standalone "WritingNewData")
    pandoc ${input_dir}/reference_guide/04_reading-and-writing.md --from markdown --to html --output ${output_dir}/reference_guide/reading-and-writing.html --filter ${script_dir}/html_links_filter.py $(append_standalone "ReadingAndWriting")
    pandoc ${input_dir}/reference_guide/05_indexing.md --from markdown --to html --output ${output_dir}/reference_guide/indexing.html --filter ${script_dir}/html_links_filter.py $(append_standalone "IndexingReference")
    pandoc ${input_dir}/reference_guide/06_graph-algorithms.md --from markdown --to html --output ${output_dir}/reference_guide/graph_algorithms.html --filter ${script_dir}/html_links_filter.py $(append_standalone "GraphAlgorithmsReference")
    pandoc ${input_dir}/reference_guide/07_graph-streams.md --from markdown --to html --output ${output_dir}/reference_guide/graph-streams.html --filter ${script_dir}/html_links_filter.py $(append_standalone "GraphStreamsReference")
    pandoc ${input_dir}/reference_guide/08_dynamic-graph-partitioner.md --from markdown --to html --output ${output_dir}/reference_guide/dynamic-graph-partitioner.html --filter ${script_dir}/html_links_filter.py $(append_standalone "DynamicGraphPartitioner")
    pandoc ${input_dir}/reference_guide/09_other-features.md --from markdown --to html --output ${output_dir}/reference_guide/other-features.html --filter ${script_dir}/html_links_filter.py $(append_standalone "OtherFeatures")
    pandoc ${input_dir}/reference_guide/10_differences.md --from markdown --to html --output ${output_dir}/reference_guide/differences.html --filter ${script_dir}/html_links_filter.py $(append_standalone "Differences")

    pandoc ${input_dir}/tutorials/01_tutorials-overview.md --from markdown --to html --output ${output_dir}/tutorials/tutorials-overview.html --filter ${script_dir}/html_links_filter.py $(append_standalone "TutorialsOverview")
    pandoc ${input_dir}/tutorials/02_analyzing-TED-talks.md --from markdown --to html --output ${output_dir}/tutorials/analyzing-TED-talks.html --filter ${script_dir}/html_links_filter.py $(append_standalone "AnalyzingTedTalks")
    pandoc ${input_dir}/tutorials/03_graphing-the-premier-league.md --from markdown --to html --output ${output_dir}/tutorials/graphing-the-premier-league.html --filter ${script_dir}/html_links_filter.py $(append_standalone "GraphingThePremierLeague")
    pandoc ${input_dir}/tutorials/04_exploring-the-european-road-network.md --from markdown --to html --output ${output_dir}/tutorials/exploring-the-european-road-network.html --filter ${script_dir}/html_links_filter.py $(append_standalone "ExploringTheEuropeanRoadNetwork")
fi


# TODO: make it optional
 for filename in $output_dir/*.html; do
     ed -s $filename <<< $'1i\n---\npermalink: /docs/:path/\n---\n.\nwq'
 done
 for filename in $output_dir/*/*.html; do
     ed -s $filename <<< $'1i\n---\npermalink: /docs/:path/\n---\n.\nwq'
 done