module.exports = {
  mage: [
    "overview",
    "installation",
     {
      type: "category",
      label: "Algorithms",
      items: [
        {
          type: "category",
          label: "Traditional Graph Analytics",
          items: [
            "algorithms/traditional-graph-analytics/betweenness-centrality-algorithm",
            "algorithms/traditional-graph-analytics/biconnected-components-algorithm",
            "algorithms/traditional-graph-analytics/bipartite-matching-algorithm",
            "algorithms/traditional-graph-analytics/bridges-algorithm",
            "algorithms/traditional-graph-analytics/community-detection-algorithm",
            "algorithms/traditional-graph-analytics/cycle-detection-algorithm",
            "algorithms/traditional-graph-analytics/graph-coloring-algorithm",
            "algorithms/traditional-graph-analytics/node-similarity-algorithm",
            "algorithms/traditional-graph-analytics/pagerank-algorithm",
            "algorithms/traditional-graph-analytics/union-find-algorithm",
          ],
        },
        {
          type: "category",
          label: "Streaming Graph Analytics",
          items: [
            "algorithms/dynamic-graph-analytics/node2vec-online-algorithm",
            "algorithms/dynamic-graph-analytics/pagerank-online-algorithm",
            "algorithms/dynamic-graph-analytics/community-detection-online-algorithm",
          ],
        },
        {
          type: "category",
          label: "Machine Learning Graph Algorithms",
          items: [
            "algorithms/machine-learning-graph-analytics/gnn-algorithm",
            "algorithms/machine-learning-graph-analytics/graph-classification-algorithm",
            "algorithms/machine-learning-graph-analytics/link-prediction-algorithm",
            "algorithms/machine-learning-graph-analytics/node-classification-algorithm",
            "algorithms/machine-learning-graph-analytics/node2vec-algorithm",
            "algorithms/machine-learning-graph-analytics/graph-clustering-algorithm",
          ],
        }
      ],
    },
    {
      type: "category",
      label: "Usage",
      items: ["usage/calling-procedures", "usage/loading-modules"],
    },
    {
      type: "category",
      label: "Tutorials",
      items: [
        "tutorials/create-a-new-module-python",
        "tutorials/create-a-new-module-cpp",
        "tutorials/run-a-query-module",
      ],
    },
    {
      type: "category",
      label: "Query modules",
      items: [
        "query-modules/cpp/betweenness-centrality",
        "query-modules/cpp/biconnected-components",
        "query-modules/cpp/bipartite-matching",
        "query-modules/cpp/bridges",
        "query-modules/cpp/community-detection-online",
        "query-modules/cpp/cycles",
        "query-modules/cpp/pagerank",
        "query-modules/cpp/pagerank-online",
        "query-modules/python/distance-calculator",
        "query-modules/python/graph-analyzer",
        "query-modules/python/graph-coloring",
        "query-modules/python/node2vec",
        "query-modules/python/node2vec-online",
        "query-modules/python/node-similarity",
        "query-modules/python/nxalg",
        "query-modules/python/set-cover",
        "query-modules/python/tsp",
        "query-modules/python/union-find",
        "query-modules/cpp/uuid-generator",
        "query-modules/python/vrp",
        "query-modules/cpp/weakly-connected-components",
      ],
    },
    {
      type: "category",
      label: "Applications",
      items: [
        "applications/bioinformatics-application",
        "applications/computer-security-application",
        "applications/drug-discovery-application",
        "applications/finance-application",
        "applications/knowledge-graph-application",
        "applications/power-grids-application",
        "applications/process-engineering-application",
        "applications/retail-application",
        "applications/social-media-application",
        "applications/telecommunication-application",
        "applications/transportation-application",
      ]
    },
    "contributing",
    {
      type: "category",
      label: "Getting help",
      items: ["getting-help/getting-help", "getting-help/faq"],
    },
  ],
};
