module.exports = {
  mage: [
    "overview",
    "installation",
    {
      type: "category",
      label: "Usage",
      items: ["usage/calling-procedures", "usage/loading-modules"],
    },
    {
      type: "category",
      label: "Tutorials",
      items: ["tutorials/create-a-new-module"],
    },
    {
      type: "category",
      label: "Query modules",
      items: [
        "query-modules/cpp/betweenness-centrality",
        "query-modules/cpp/biconnected-components",
        "query-modules/cpp/bipartite-matching",
        "query-modules/cpp/bridges",
        "query-modules/cpp/cycles",
        "query-modules/cpp/pagerank",
        "query-modules/cpp/pagerank-online",
        "query-modules/python/distance-calculator",
        "query-modules/python/graph-analyzer",
        "query-modules/python/graph-coloring",
        "query-modules/python/node2vec-online",
        "query-modules/python/node-similarity",
        "query-modules/python/nxalg",
        "query-modules/python/set-cover",
        "query-modules/python/tsp",
        "query-modules/python/union-find",
        "query-modules/cpp/uuid-generator",
        "query-modules/python/vrp",
        "query-modules/cpp/weakly-connected-components",
      ],
    },
    "contributing",
    {
      type: "category",
      label: "Getting help",
      items: ["getting-help/getting-help", "getting-help/faq"],
    },
  ],
};
